version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    # container_name: removed to avoid name conflicts
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_2_INIT_USERNAME=influx_admin
      - INFLUXDB_2_INIT_PASSWORD=InfluxPass123!
      - INFLUXDB_2_INIT_ORG=my-org
      - INFLUXDB_2_INIT_BUCKET=my-bucket
      - INFLUXDB_2_INIT_TOKEN=my-token-0123456789
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - dbnet

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=PgPass123!
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dbnet

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=PgAdminPass123!
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dbnet

  cassandra:
    image: cassandra:4.1
    # remove container_name to avoid conflicts
    restart: unless-stopped
    # change host port mapping if 9042 is busy (host:container)
    ports:
      - "9043:9042"   # <-- mapped to host 9043 to avoid common conflicts
    platform: linux/arm64/v8   # try native ARM build first; if it fails change to linux/amd64
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      dbnet:
        ipv4_address: 172.28.0.10
    healthcheck:
      test: ["CMD-SHELL", "nodetool status >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

  cassandra-web:
    image: dcagatay/cassandra-web:latest
    restart: unless-stopped
    depends_on:
      - cassandra
    ports:
      - "3000:3000"
    environment:
      - CASSANDRA_HOST_IPS=172.28.0.10
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    # If this image is not multi-arch, you can force amd64 emulation:
    # platform: linux/amd64
    networks:
      dbnet:
        ipv4_address: 172.28.0.20

volumes:
  influxdb-data:
  pgdata:
  pgadmin-data:
  cassandra-data:

networks:
  dbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
